sudo: false
language: objective-c
os: osx
osx_image: xcode10

cache:
  directories:
  - Carthage

matrix:
  include:
    - env: ACTION=test_ios12
    - env: ACTION=test_ios11
    - env: ACTION=test_tvos12
    - env: ACTION=test_tvos11
    - env: ACTION=test_ios_swift3
    - env: ACTION=test_ios_swift4
    - env: ACTION=test_tvos_swift3
    - env: ACTION=test_tvos_swift4
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift3
    - osx_image: xcode9.4
      env: ACTION=test_xcode9_ios_swift4
    - env: ACTION=pod_lint
    - env: ACTION=carthage_build

before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --cache-builds

script:
  - instruments -s devices # List all available simulators
  - bundle exec fastlane $ACTION

env:
  global:
    secure: AFszIbBJIhT73In7hDE3IEAR39w2+lva0Jra/gFXnIP6oF4GNmPJljztDZ0If8wE+KQ7HTJ514lpjsIP+6maSXOBX72Xh04jBtIRlmXuLBbc0W3FmkQl6JU8QZmY/aYwO2X6WyEyzuOzl2vW465mBpGu1VM+hwHyDbDGbLln0is=
