sudo: false
language: objective-c
os: osx
osx_image: xcode11

matrix:
  include:
    - env: ACTION=test_ios13 PLATFORM=iOS
    - env: ACTION=test_ios12 PLATFORM=iOS
    - env: ACTION=test_tvos13 PLATFORM=tvOS
    - env: ACTION=test_tvos12 PLATFORM=tvOS
    - env: ACTION=test_ios_swift4 PLATFORM=iOS
    - env: ACTION=test_ios_swift4_2 PLATFORM=iOS
    - env: ACTION=test_tvos_swift4 PLATFORM=tvOS
    - env: ACTION=test_tvos_swift4_2 PLATFORM=tvOS
    - env: ACTION=pod_lint PLATFORM="iOS,tvOS"
    - env: ACTION=carthage_build PLATFORM="iOS,tvOS"

script:
  - instruments -s devices # List all available simulators
  - FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=120 bundle exec fastlane $ACTION

env:
  global:
    secure: AFszIbBJIhT73In7hDE3IEAR39w2+lva0Jra/gFXnIP6oF4GNmPJljztDZ0If8wE+KQ7HTJ514lpjsIP+6maSXOBX72Xh04jBtIRlmXuLBbc0W3FmkQl6JU8QZmY/aYwO2X6WyEyzuOzl2vW465mBpGu1VM+hwHyDbDGbLln0is=
